CREATE TABLE document (
    doc_transaction_id BIGINT NOT NULL PRIMARY KEY,
    seq_no INT NOT NULL,
    doc_path VARCHAR(500),
    doc_name VARCHAR(255),
    original_file_name VARCHAR(255),
    original_file_type VARCHAR(100),
    created_date TIMESTAMP,
    created_by VARCHAR(100)
);

CREATE TABLE upload_document (
    doc_transaction_id BIGINT PRIMARY KEY,
    doc_transaction_seq_no INT NOT NULL,
    case_no VARCHAR(50),
    doc_type VARCHAR(50),
    doc_class VARCHAR(50),
    destination_company_code VARCHAR(20),
    destination_office_code VARCHAR(20),
    total_document INT,
    doc_status VARCHAR(20),
    hire_no VARCHAR(50),
    created_date TIMESTAMP,
    created_by VARCHAR(100),
    updated_date TIMESTAMP,
    updated_by VARCHAR(100),
    campaign_code VARCHAR(20),
    service_code VARCHAR(20),
    bu_code VARCHAR(20),
    mkt_code VARCHAR(20),
    branch_id VARCHAR(20)
);

INSERT INTO upload_document (
    doc_transaction_id,
    doc_transaction_seq_no,
    case_no,
    doc_type,
    doc_class,
    destination_company_code,
    destination_office_code,
    total_document,
    doc_status,
    hire_no,
    created_date,
    created_by,
    updated_date,
    updated_by,
    campaign_code,
    service_code,
    bu_code,
    mkt_code,
    branch_id
) VALUES (
    1,
    1,
    'CASE00001',
    'Invoice',
    'Finance',
    'COMP002',
    'OFFICE004',
    6,
    'NEW',
    'HIRE998877',
    '2025-04-18 09:00:00',
    'system_user',
    '2025-04-18 10:00:00',
    'admin_user',
    'CampaignCode1234',
    'Service1234',
    'Bu123434',
    'Mkt1235',
    'Branch1234'
);

INSERT INTO upload_document (
    doc_transaction_id,
    doc_transaction_seq_no,
    case_no,
    doc_type,
    doc_class,
    destination_company_code,
    destination_office_code,
    total_document,
    doc_status,
    hire_no,
    created_date,
    created_by,
    updated_date,
    updated_by,
    campaign_code,
    service_code,
    bu_code,
    mkt_code,
    branch_id
) VALUES (
    2,
    1,
    'CASE000002',
    'Invoice',
    'Finance',
    'COMP002',
    'OFFICE004',
    6,
    'NEW',
    'HIRE998877',
    '2025-04-18 09:00:00',
    'system_user',
    '2025-04-18 10:00:00',
    'admin_user',
    'CampaignCode1234',
    'Service1234',
    'Bu123434',
    'Mkt1235',
    'Branch1234'
);
